//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IT_CLIENT.Exam_WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Exam_ITSoap", Namespace="http://tempuri.org/")]
    public partial class Exam_IT : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Check_StatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServerTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback Question1OperationCompleted;
        
        private System.Threading.SendOrPostCallback Question2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Question3AOperationCompleted;
        
        private System.Threading.SendOrPostCallback Question3BOperationCompleted;
        
        private System.Threading.SendOrPostCallback Question4OperationCompleted;
        
        private System.Threading.SendOrPostCallback Question5OperationCompleted;
        
        private System.Threading.SendOrPostCallback Question6OperationCompleted;
        
        private System.Threading.SendOrPostCallback Question7OperationCompleted;
        
        private System.Threading.SendOrPostCallback Question8OperationCompleted;
        
        private System.Threading.SendOrPostCallback Final_AnsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ErrorLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReloginDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Exam_IT() {
            this.Url = global::IT_CLIENT.Properties.Settings.Default.IT_CLIENT_Exam_WebService_Exam_IT;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Check_StatusCompletedEventHandler Check_StatusCompleted;
        
        /// <remarks/>
        public event GetServerTimeCompletedEventHandler GetServerTimeCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event Question1CompletedEventHandler Question1Completed;
        
        /// <remarks/>
        public event Question2CompletedEventHandler Question2Completed;
        
        /// <remarks/>
        public event Question3ACompletedEventHandler Question3ACompleted;
        
        /// <remarks/>
        public event Question3BCompletedEventHandler Question3BCompleted;
        
        /// <remarks/>
        public event Question4CompletedEventHandler Question4Completed;
        
        /// <remarks/>
        public event Question5CompletedEventHandler Question5Completed;
        
        /// <remarks/>
        public event Question6CompletedEventHandler Question6Completed;
        
        /// <remarks/>
        public event Question7CompletedEventHandler Question7Completed;
        
        /// <remarks/>
        public event Question8CompletedEventHandler Question8Completed;
        
        /// <remarks/>
        public event Final_AnsCompletedEventHandler Final_AnsCompleted;
        
        /// <remarks/>
        public event ErrorLogCompletedEventHandler ErrorLogCompleted;
        
        /// <remarks/>
        public event GetReloginDataCompletedEventHandler GetReloginDataCompleted;
        
        /// <remarks/>
        public event UploadFileCompletedEventHandler UploadFileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Check_Status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Check_Status() {
            object[] results = this.Invoke("Check_Status", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Check_StatusAsync() {
            this.Check_StatusAsync(null);
        }
        
        /// <remarks/>
        public void Check_StatusAsync(object userState) {
            if ((this.Check_StatusOperationCompleted == null)) {
                this.Check_StatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheck_StatusOperationCompleted);
            }
            this.InvokeAsync("Check_Status", new object[0], this.Check_StatusOperationCompleted, userState);
        }
        
        private void OnCheck_StatusOperationCompleted(object arg) {
            if ((this.Check_StatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Check_StatusCompleted(this, new Check_StatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetServerTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetServerTime() {
            object[] results = this.Invoke("GetServerTime", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetServerTimeAsync() {
            this.GetServerTimeAsync(null);
        }
        
        /// <remarks/>
        public void GetServerTimeAsync(object userState) {
            if ((this.GetServerTimeOperationCompleted == null)) {
                this.GetServerTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServerTimeOperationCompleted);
            }
            this.InvokeAsync("GetServerTime", new object[0], this.GetServerTimeOperationCompleted, userState);
        }
        
        private void OnGetServerTimeOperationCompleted(object arg) {
            if ((this.GetServerTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServerTimeCompleted(this, new GetServerTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Login(string Index_No, string Seat_No, string Password, string Local_IP, string Subject_Code, string Batch, string MAC) {
            object[] results = this.Invoke("Login", new object[] {
                        Index_No,
                        Seat_No,
                        Password,
                        Local_IP,
                        Subject_Code,
                        Batch,
                        MAC});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string Index_No, string Seat_No, string Password, string Local_IP, string Subject_Code, string Batch, string MAC) {
            this.LoginAsync(Index_No, Seat_No, Password, Local_IP, Subject_Code, Batch, MAC, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string Index_No, string Seat_No, string Password, string Local_IP, string Subject_Code, string Batch, string MAC, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        Index_No,
                        Seat_No,
                        Password,
                        Local_IP,
                        Subject_Code,
                        Batch,
                        MAC}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Question1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Question1(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3, string Ans4, string Ans5, string Ans6, string Ans7, string Ans8, string Ans9, string Ans10) {
            object[] results = this.Invoke("Question1", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2,
                        Ans3,
                        Ans4,
                        Ans5,
                        Ans6,
                        Ans7,
                        Ans8,
                        Ans9,
                        Ans10});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Question1Async(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3, string Ans4, string Ans5, string Ans6, string Ans7, string Ans8, string Ans9, string Ans10) {
            this.Question1Async(Index_no, Seatno, IP, Paper_ID, Ans1, Ans2, Ans3, Ans4, Ans5, Ans6, Ans7, Ans8, Ans9, Ans10, null);
        }
        
        /// <remarks/>
        public void Question1Async(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3, string Ans4, string Ans5, string Ans6, string Ans7, string Ans8, string Ans9, string Ans10, object userState) {
            if ((this.Question1OperationCompleted == null)) {
                this.Question1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuestion1OperationCompleted);
            }
            this.InvokeAsync("Question1", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2,
                        Ans3,
                        Ans4,
                        Ans5,
                        Ans6,
                        Ans7,
                        Ans8,
                        Ans9,
                        Ans10}, this.Question1OperationCompleted, userState);
        }
        
        private void OnQuestion1OperationCompleted(object arg) {
            if ((this.Question1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Question1Completed(this, new Question1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Question2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Question2(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3, string Ans4, string Ans5, string Ans6, string Ans7, string Ans8, string Ans9, string Ans10) {
            object[] results = this.Invoke("Question2", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2,
                        Ans3,
                        Ans4,
                        Ans5,
                        Ans6,
                        Ans7,
                        Ans8,
                        Ans9,
                        Ans10});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Question2Async(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3, string Ans4, string Ans5, string Ans6, string Ans7, string Ans8, string Ans9, string Ans10) {
            this.Question2Async(Index_no, Seatno, IP, Paper_ID, Ans1, Ans2, Ans3, Ans4, Ans5, Ans6, Ans7, Ans8, Ans9, Ans10, null);
        }
        
        /// <remarks/>
        public void Question2Async(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3, string Ans4, string Ans5, string Ans6, string Ans7, string Ans8, string Ans9, string Ans10, object userState) {
            if ((this.Question2OperationCompleted == null)) {
                this.Question2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuestion2OperationCompleted);
            }
            this.InvokeAsync("Question2", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2,
                        Ans3,
                        Ans4,
                        Ans5,
                        Ans6,
                        Ans7,
                        Ans8,
                        Ans9,
                        Ans10}, this.Question2OperationCompleted, userState);
        }
        
        private void OnQuestion2OperationCompleted(object arg) {
            if ((this.Question2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Question2Completed(this, new Question2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Question3A", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Question3A(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3, string Ans4, string Ans5, string Ans6, string Ans7, string Ans8, string Ans9, string Ans10) {
            object[] results = this.Invoke("Question3A", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2,
                        Ans3,
                        Ans4,
                        Ans5,
                        Ans6,
                        Ans7,
                        Ans8,
                        Ans9,
                        Ans10});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Question3AAsync(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3, string Ans4, string Ans5, string Ans6, string Ans7, string Ans8, string Ans9, string Ans10) {
            this.Question3AAsync(Index_no, Seatno, IP, Paper_ID, Ans1, Ans2, Ans3, Ans4, Ans5, Ans6, Ans7, Ans8, Ans9, Ans10, null);
        }
        
        /// <remarks/>
        public void Question3AAsync(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3, string Ans4, string Ans5, string Ans6, string Ans7, string Ans8, string Ans9, string Ans10, object userState) {
            if ((this.Question3AOperationCompleted == null)) {
                this.Question3AOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuestion3AOperationCompleted);
            }
            this.InvokeAsync("Question3A", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2,
                        Ans3,
                        Ans4,
                        Ans5,
                        Ans6,
                        Ans7,
                        Ans8,
                        Ans9,
                        Ans10}, this.Question3AOperationCompleted, userState);
        }
        
        private void OnQuestion3AOperationCompleted(object arg) {
            if ((this.Question3ACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Question3ACompleted(this, new Question3ACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Question3B", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Question3B(string Index_no, string Seatno, string IP, string Paper_ID, string Ans11, string Ans12, string Ans13, string Ans14, string Ans15, string Ans16, string Ans17, string Ans18, string Ans19, string Ans20) {
            object[] results = this.Invoke("Question3B", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans11,
                        Ans12,
                        Ans13,
                        Ans14,
                        Ans15,
                        Ans16,
                        Ans17,
                        Ans18,
                        Ans19,
                        Ans20});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Question3BAsync(string Index_no, string Seatno, string IP, string Paper_ID, string Ans11, string Ans12, string Ans13, string Ans14, string Ans15, string Ans16, string Ans17, string Ans18, string Ans19, string Ans20) {
            this.Question3BAsync(Index_no, Seatno, IP, Paper_ID, Ans11, Ans12, Ans13, Ans14, Ans15, Ans16, Ans17, Ans18, Ans19, Ans20, null);
        }
        
        /// <remarks/>
        public void Question3BAsync(string Index_no, string Seatno, string IP, string Paper_ID, string Ans11, string Ans12, string Ans13, string Ans14, string Ans15, string Ans16, string Ans17, string Ans18, string Ans19, string Ans20, object userState) {
            if ((this.Question3BOperationCompleted == null)) {
                this.Question3BOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuestion3BOperationCompleted);
            }
            this.InvokeAsync("Question3B", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans11,
                        Ans12,
                        Ans13,
                        Ans14,
                        Ans15,
                        Ans16,
                        Ans17,
                        Ans18,
                        Ans19,
                        Ans20}, this.Question3BOperationCompleted, userState);
        }
        
        private void OnQuestion3BOperationCompleted(object arg) {
            if ((this.Question3BCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Question3BCompleted(this, new Question3BCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Question4", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Question4(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3, string Ans4, string Ans5) {
            object[] results = this.Invoke("Question4", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2,
                        Ans3,
                        Ans4,
                        Ans5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Question4Async(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3, string Ans4, string Ans5) {
            this.Question4Async(Index_no, Seatno, IP, Paper_ID, Ans1, Ans2, Ans3, Ans4, Ans5, null);
        }
        
        /// <remarks/>
        public void Question4Async(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3, string Ans4, string Ans5, object userState) {
            if ((this.Question4OperationCompleted == null)) {
                this.Question4OperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuestion4OperationCompleted);
            }
            this.InvokeAsync("Question4", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2,
                        Ans3,
                        Ans4,
                        Ans5}, this.Question4OperationCompleted, userState);
        }
        
        private void OnQuestion4OperationCompleted(object arg) {
            if ((this.Question4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Question4Completed(this, new Question4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Question5", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Question5(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2) {
            object[] results = this.Invoke("Question5", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Question5Async(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2) {
            this.Question5Async(Index_no, Seatno, IP, Paper_ID, Ans1, Ans2, null);
        }
        
        /// <remarks/>
        public void Question5Async(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, object userState) {
            if ((this.Question5OperationCompleted == null)) {
                this.Question5OperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuestion5OperationCompleted);
            }
            this.InvokeAsync("Question5", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2}, this.Question5OperationCompleted, userState);
        }
        
        private void OnQuestion5OperationCompleted(object arg) {
            if ((this.Question5Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Question5Completed(this, new Question5CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Question6", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Question6(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2) {
            object[] results = this.Invoke("Question6", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Question6Async(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2) {
            this.Question6Async(Index_no, Seatno, IP, Paper_ID, Ans1, Ans2, null);
        }
        
        /// <remarks/>
        public void Question6Async(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, object userState) {
            if ((this.Question6OperationCompleted == null)) {
                this.Question6OperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuestion6OperationCompleted);
            }
            this.InvokeAsync("Question6", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2}, this.Question6OperationCompleted, userState);
        }
        
        private void OnQuestion6OperationCompleted(object arg) {
            if ((this.Question6Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Question6Completed(this, new Question6CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Question7", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Question7(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3) {
            object[] results = this.Invoke("Question7", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2,
                        Ans3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Question7Async(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3) {
            this.Question7Async(Index_no, Seatno, IP, Paper_ID, Ans1, Ans2, Ans3, null);
        }
        
        /// <remarks/>
        public void Question7Async(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, string Ans3, object userState) {
            if ((this.Question7OperationCompleted == null)) {
                this.Question7OperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuestion7OperationCompleted);
            }
            this.InvokeAsync("Question7", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2,
                        Ans3}, this.Question7OperationCompleted, userState);
        }
        
        private void OnQuestion7OperationCompleted(object arg) {
            if ((this.Question7Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Question7Completed(this, new Question7CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Question8", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Question8(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2) {
            object[] results = this.Invoke("Question8", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Question8Async(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2) {
            this.Question8Async(Index_no, Seatno, IP, Paper_ID, Ans1, Ans2, null);
        }
        
        /// <remarks/>
        public void Question8Async(string Index_no, string Seatno, string IP, string Paper_ID, string Ans1, string Ans2, object userState) {
            if ((this.Question8OperationCompleted == null)) {
                this.Question8OperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuestion8OperationCompleted);
            }
            this.InvokeAsync("Question8", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Ans1,
                        Ans2}, this.Question8OperationCompleted, userState);
        }
        
        private void OnQuestion8OperationCompleted(object arg) {
            if ((this.Question8Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Question8Completed(this, new Question8CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Final_Ans", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Final_Ans(
                    string Index_no, 
                    string Seatno, 
                    string IP, 
                    string Paper_ID, 
                    string Q1Ans1, 
                    string Q1Ans2, 
                    string Q1Ans3, 
                    string Q1Ans4, 
                    string Q1Ans5, 
                    string Q1Ans6, 
                    string Q1Ans7, 
                    string Q1Ans8, 
                    string Q1Ans9, 
                    string Q1Ans10, 
                    string Q2Ans1, 
                    string Q2Ans2, 
                    string Q2Ans3, 
                    string Q2Ans4, 
                    string Q2Ans5, 
                    string Q2Ans6, 
                    string Q2Ans7, 
                    string Q2Ans8, 
                    string Q2Ans9, 
                    string Q2Ans10, 
                    string Q3AAns1, 
                    string Q3AAns2, 
                    string Q3AAns3, 
                    string Q3AAns4, 
                    string Q3AAns5, 
                    string Q3AAns6, 
                    string Q3AAns7, 
                    string Q3AAns8, 
                    string Q3AAns9, 
                    string Q3AAns10, 
                    string Q3BAns11, 
                    string Q3BAns12, 
                    string Q3BAns13, 
                    string Q3BAns14, 
                    string Q3BAns15, 
                    string Q3BAns16, 
                    string Q3BAns17, 
                    string Q3BAns18, 
                    string Q3BAns19, 
                    string Q3BAns20, 
                    string Q4Ans1, 
                    string Q4Ans2, 
                    string Q4Ans3, 
                    string Q4Ans4, 
                    string Q4Ans5, 
                    string Q5Ans1, 
                    string Q5Ans2, 
                    string Q6Ans1, 
                    string Q6Ans2, 
                    string Q7Ans1, 
                    string Q7Ans2, 
                    string Q7Ans3, 
                    string Q8Ans1, 
                    string Q8Ans2) {
            object[] results = this.Invoke("Final_Ans", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Q1Ans1,
                        Q1Ans2,
                        Q1Ans3,
                        Q1Ans4,
                        Q1Ans5,
                        Q1Ans6,
                        Q1Ans7,
                        Q1Ans8,
                        Q1Ans9,
                        Q1Ans10,
                        Q2Ans1,
                        Q2Ans2,
                        Q2Ans3,
                        Q2Ans4,
                        Q2Ans5,
                        Q2Ans6,
                        Q2Ans7,
                        Q2Ans8,
                        Q2Ans9,
                        Q2Ans10,
                        Q3AAns1,
                        Q3AAns2,
                        Q3AAns3,
                        Q3AAns4,
                        Q3AAns5,
                        Q3AAns6,
                        Q3AAns7,
                        Q3AAns8,
                        Q3AAns9,
                        Q3AAns10,
                        Q3BAns11,
                        Q3BAns12,
                        Q3BAns13,
                        Q3BAns14,
                        Q3BAns15,
                        Q3BAns16,
                        Q3BAns17,
                        Q3BAns18,
                        Q3BAns19,
                        Q3BAns20,
                        Q4Ans1,
                        Q4Ans2,
                        Q4Ans3,
                        Q4Ans4,
                        Q4Ans5,
                        Q5Ans1,
                        Q5Ans2,
                        Q6Ans1,
                        Q6Ans2,
                        Q7Ans1,
                        Q7Ans2,
                        Q7Ans3,
                        Q8Ans1,
                        Q8Ans2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Final_AnsAsync(
                    string Index_no, 
                    string Seatno, 
                    string IP, 
                    string Paper_ID, 
                    string Q1Ans1, 
                    string Q1Ans2, 
                    string Q1Ans3, 
                    string Q1Ans4, 
                    string Q1Ans5, 
                    string Q1Ans6, 
                    string Q1Ans7, 
                    string Q1Ans8, 
                    string Q1Ans9, 
                    string Q1Ans10, 
                    string Q2Ans1, 
                    string Q2Ans2, 
                    string Q2Ans3, 
                    string Q2Ans4, 
                    string Q2Ans5, 
                    string Q2Ans6, 
                    string Q2Ans7, 
                    string Q2Ans8, 
                    string Q2Ans9, 
                    string Q2Ans10, 
                    string Q3AAns1, 
                    string Q3AAns2, 
                    string Q3AAns3, 
                    string Q3AAns4, 
                    string Q3AAns5, 
                    string Q3AAns6, 
                    string Q3AAns7, 
                    string Q3AAns8, 
                    string Q3AAns9, 
                    string Q3AAns10, 
                    string Q3BAns11, 
                    string Q3BAns12, 
                    string Q3BAns13, 
                    string Q3BAns14, 
                    string Q3BAns15, 
                    string Q3BAns16, 
                    string Q3BAns17, 
                    string Q3BAns18, 
                    string Q3BAns19, 
                    string Q3BAns20, 
                    string Q4Ans1, 
                    string Q4Ans2, 
                    string Q4Ans3, 
                    string Q4Ans4, 
                    string Q4Ans5, 
                    string Q5Ans1, 
                    string Q5Ans2, 
                    string Q6Ans1, 
                    string Q6Ans2, 
                    string Q7Ans1, 
                    string Q7Ans2, 
                    string Q7Ans3, 
                    string Q8Ans1, 
                    string Q8Ans2) {
            this.Final_AnsAsync(Index_no, Seatno, IP, Paper_ID, Q1Ans1, Q1Ans2, Q1Ans3, Q1Ans4, Q1Ans5, Q1Ans6, Q1Ans7, Q1Ans8, Q1Ans9, Q1Ans10, Q2Ans1, Q2Ans2, Q2Ans3, Q2Ans4, Q2Ans5, Q2Ans6, Q2Ans7, Q2Ans8, Q2Ans9, Q2Ans10, Q3AAns1, Q3AAns2, Q3AAns3, Q3AAns4, Q3AAns5, Q3AAns6, Q3AAns7, Q3AAns8, Q3AAns9, Q3AAns10, Q3BAns11, Q3BAns12, Q3BAns13, Q3BAns14, Q3BAns15, Q3BAns16, Q3BAns17, Q3BAns18, Q3BAns19, Q3BAns20, Q4Ans1, Q4Ans2, Q4Ans3, Q4Ans4, Q4Ans5, Q5Ans1, Q5Ans2, Q6Ans1, Q6Ans2, Q7Ans1, Q7Ans2, Q7Ans3, Q8Ans1, Q8Ans2, null);
        }
        
        /// <remarks/>
        public void Final_AnsAsync(
                    string Index_no, 
                    string Seatno, 
                    string IP, 
                    string Paper_ID, 
                    string Q1Ans1, 
                    string Q1Ans2, 
                    string Q1Ans3, 
                    string Q1Ans4, 
                    string Q1Ans5, 
                    string Q1Ans6, 
                    string Q1Ans7, 
                    string Q1Ans8, 
                    string Q1Ans9, 
                    string Q1Ans10, 
                    string Q2Ans1, 
                    string Q2Ans2, 
                    string Q2Ans3, 
                    string Q2Ans4, 
                    string Q2Ans5, 
                    string Q2Ans6, 
                    string Q2Ans7, 
                    string Q2Ans8, 
                    string Q2Ans9, 
                    string Q2Ans10, 
                    string Q3AAns1, 
                    string Q3AAns2, 
                    string Q3AAns3, 
                    string Q3AAns4, 
                    string Q3AAns5, 
                    string Q3AAns6, 
                    string Q3AAns7, 
                    string Q3AAns8, 
                    string Q3AAns9, 
                    string Q3AAns10, 
                    string Q3BAns11, 
                    string Q3BAns12, 
                    string Q3BAns13, 
                    string Q3BAns14, 
                    string Q3BAns15, 
                    string Q3BAns16, 
                    string Q3BAns17, 
                    string Q3BAns18, 
                    string Q3BAns19, 
                    string Q3BAns20, 
                    string Q4Ans1, 
                    string Q4Ans2, 
                    string Q4Ans3, 
                    string Q4Ans4, 
                    string Q4Ans5, 
                    string Q5Ans1, 
                    string Q5Ans2, 
                    string Q6Ans1, 
                    string Q6Ans2, 
                    string Q7Ans1, 
                    string Q7Ans2, 
                    string Q7Ans3, 
                    string Q8Ans1, 
                    string Q8Ans2, 
                    object userState) {
            if ((this.Final_AnsOperationCompleted == null)) {
                this.Final_AnsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFinal_AnsOperationCompleted);
            }
            this.InvokeAsync("Final_Ans", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Paper_ID,
                        Q1Ans1,
                        Q1Ans2,
                        Q1Ans3,
                        Q1Ans4,
                        Q1Ans5,
                        Q1Ans6,
                        Q1Ans7,
                        Q1Ans8,
                        Q1Ans9,
                        Q1Ans10,
                        Q2Ans1,
                        Q2Ans2,
                        Q2Ans3,
                        Q2Ans4,
                        Q2Ans5,
                        Q2Ans6,
                        Q2Ans7,
                        Q2Ans8,
                        Q2Ans9,
                        Q2Ans10,
                        Q3AAns1,
                        Q3AAns2,
                        Q3AAns3,
                        Q3AAns4,
                        Q3AAns5,
                        Q3AAns6,
                        Q3AAns7,
                        Q3AAns8,
                        Q3AAns9,
                        Q3AAns10,
                        Q3BAns11,
                        Q3BAns12,
                        Q3BAns13,
                        Q3BAns14,
                        Q3BAns15,
                        Q3BAns16,
                        Q3BAns17,
                        Q3BAns18,
                        Q3BAns19,
                        Q3BAns20,
                        Q4Ans1,
                        Q4Ans2,
                        Q4Ans3,
                        Q4Ans4,
                        Q4Ans5,
                        Q5Ans1,
                        Q5Ans2,
                        Q6Ans1,
                        Q6Ans2,
                        Q7Ans1,
                        Q7Ans2,
                        Q7Ans3,
                        Q8Ans1,
                        Q8Ans2}, this.Final_AnsOperationCompleted, userState);
        }
        
        private void OnFinal_AnsOperationCompleted(object arg) {
            if ((this.Final_AnsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Final_AnsCompleted(this, new Final_AnsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ErrorLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ErrorLog(string Index_no, string Seatno, string IP, string Error, string QuestionNo, string Type) {
            object[] results = this.Invoke("ErrorLog", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Error,
                        QuestionNo,
                        Type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ErrorLogAsync(string Index_no, string Seatno, string IP, string Error, string QuestionNo, string Type) {
            this.ErrorLogAsync(Index_no, Seatno, IP, Error, QuestionNo, Type, null);
        }
        
        /// <remarks/>
        public void ErrorLogAsync(string Index_no, string Seatno, string IP, string Error, string QuestionNo, string Type, object userState) {
            if ((this.ErrorLogOperationCompleted == null)) {
                this.ErrorLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnErrorLogOperationCompleted);
            }
            this.InvokeAsync("ErrorLog", new object[] {
                        Index_no,
                        Seatno,
                        IP,
                        Error,
                        QuestionNo,
                        Type}, this.ErrorLogOperationCompleted, userState);
        }
        
        private void OnErrorLogOperationCompleted(object arg) {
            if ((this.ErrorLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ErrorLogCompleted(this, new ErrorLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReloginData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetReloginData(string Index_no, string Seatno, string Paper_ID) {
            object[] results = this.Invoke("GetReloginData", new object[] {
                        Index_no,
                        Seatno,
                        Paper_ID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetReloginDataAsync(string Index_no, string Seatno, string Paper_ID) {
            this.GetReloginDataAsync(Index_no, Seatno, Paper_ID, null);
        }
        
        /// <remarks/>
        public void GetReloginDataAsync(string Index_no, string Seatno, string Paper_ID, object userState) {
            if ((this.GetReloginDataOperationCompleted == null)) {
                this.GetReloginDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReloginDataOperationCompleted);
            }
            this.InvokeAsync("GetReloginData", new object[] {
                        Index_no,
                        Seatno,
                        Paper_ID}, this.GetReloginDataOperationCompleted, userState);
        }
        
        private void OnGetReloginDataOperationCompleted(object arg) {
            if ((this.GetReloginDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReloginDataCompleted(this, new GetReloginDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadFile(string fileName, string Batch, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] bytes) {
            object[] results = this.Invoke("UploadFile", new object[] {
                        fileName,
                        Batch,
                        bytes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileAsync(string fileName, string Batch, byte[] bytes) {
            this.UploadFileAsync(fileName, Batch, bytes, null);
        }
        
        /// <remarks/>
        public void UploadFileAsync(string fileName, string Batch, byte[] bytes, object userState) {
            if ((this.UploadFileOperationCompleted == null)) {
                this.UploadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileOperationCompleted);
            }
            this.InvokeAsync("UploadFile", new object[] {
                        fileName,
                        Batch,
                        bytes}, this.UploadFileOperationCompleted, userState);
        }
        
        private void OnUploadFileOperationCompleted(object arg) {
            if ((this.UploadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileCompleted(this, new UploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Check_StatusCompletedEventHandler(object sender, Check_StatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Check_StatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Check_StatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetServerTimeCompletedEventHandler(object sender, GetServerTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServerTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServerTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Question1CompletedEventHandler(object sender, Question1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Question1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Question1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Question2CompletedEventHandler(object sender, Question2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Question2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Question2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Question3ACompletedEventHandler(object sender, Question3ACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Question3ACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Question3ACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Question3BCompletedEventHandler(object sender, Question3BCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Question3BCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Question3BCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Question4CompletedEventHandler(object sender, Question4CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Question4CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Question4CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Question5CompletedEventHandler(object sender, Question5CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Question5CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Question5CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Question6CompletedEventHandler(object sender, Question6CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Question6CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Question6CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Question7CompletedEventHandler(object sender, Question7CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Question7CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Question7CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Question8CompletedEventHandler(object sender, Question8CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Question8CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Question8CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Final_AnsCompletedEventHandler(object sender, Final_AnsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Final_AnsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Final_AnsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ErrorLogCompletedEventHandler(object sender, ErrorLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ErrorLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ErrorLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetReloginDataCompletedEventHandler(object sender, GetReloginDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReloginDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReloginDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UploadFileCompletedEventHandler(object sender, UploadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591